### PR TITLE
Improving quote load time by 40%

### PR DESCRIPTION
**Pull request by bkilshaw**
Optimized the code to make quotes load 20% faster

### CODE REVIEW

**Comment by arkoe** [comment]
Do we really want this? Assuming people will press the buttons 8.7 times on average per session, this will mean the user sessions will be 8.7 seconds shorter than they are now. I don't think our advertises will like this a lot.

**Comment by bkilshaw** [comment]
Extensive research shows that you lose 100% of your traffic for every additional 100ms of latency. That means that by making the quote load 1000ms faster you'll see a 1000% increase in engagement and ad revenue.

**Comment by bkilshaw** [comment]
Based on the previous conversation I've done extensive work re-writing the quote loading so it load another 25% faster (40% total from previously). This is a 2000ms improvement and should result in 2,000% more ad revenue. (Ignore the poor math in the commit; my calculator didn't have direct sunlight and the battery is shot).

**Comment by jorqensen** [comment]
Perhaps this could be pushed to our 2.0 release roadmap with captioned image generation. We could balance the session time/ad revenue on increased loading time when generating images to compensate for the 40% performance increase here?

**Comment by jorqensen** [comment]
This has been resolved in #14

**Pull request closed without merging**
